### ISSUE TITLE
Resources created in a different location to the resource group fail to update

### ISSUE THREAD

**Issue by lostdoco** [Azure/AzOps-Accelerator#59]
**Describe the bug**
When a resource is created with a location different to that of the resource group, updating the resource via ARM template fails on the AzPush

**Steps to reproduce**

1. Create a resource group in a region, eg australiaeast
2. Create a resource in a different region via the portal in the same resource groups, eg, laworkspace in southeastasia
3. Run the AzOps - Pull action and wait for the resource to be represented as ARM in the repo
4. modify the resource ARM values that can be changed, eg, set retention from 30 -> 300 days
5. create a pr and wait for AzOps - Push action to fail (screenshot)
6. in this case the AzOps - Push scripts interprets the change in arm as a new deployment rather than updating due to the resource group location setting the resource to a different location

**Screenshots**

![image](https://user-images.githubusercontent.com/52767190/112770830-57e28080-9074-11eb-9efa-3e0b1796fb05.png)

**Additional**
This seems to be due to the process in **AzOps - Pull** action that converts the resources into templates does not check/record/honour the location of the actual resource and instead sets it to **"location": "[resourceGroup().location]"** which is fine if everything in the same RG is in the same region, but fails if the regions mismatch between resources.

**Comment by ljtill** [comment]
Thanks for reporting this issue @lostdoco. We should be able to update this value within the AzOps module when we generate the templates. I'll update this thread shortly when I have an update.

**Comment by lostdoco** [comment]
Thankyou @ljtill - happy to help

**Comment by ljtill** [comment]
@lostdoco changes merged and release created. https://github.com/Azure/AzOps/pull/250
Upon the next run of `AzOps - Pull` the location property will update.
